In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn import preprocessing 

In [8]:
data = pd.read_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/train1.csv')
data.head()

1111       22.7       37.2         21         38      23.39      37.29  \
0  1112  21.500000  41.045000  20.500000  39.133333  22.926667  39.526667   
1  1113  21.666667  38.000000  22.600000  35.700000  21.890000  36.590000   
2  1114  23.290000  38.530000  21.671429  38.000000  24.290000  36.200000   
3  1115  24.000000  42.560000  26.830000  34.356000  26.530000  40.333333   
4  1116  18.390000  43.363333  17.700000  42.433333  19.290000  42.500000   

   22.83285714  34.94285714       20.5 ...       45.36   20.2  38.66333333  \
0         21.7    34.126667  18.633333 ...   34.663333  19.73    37.933333   
1         22.0    35.530000  19.000000 ...   38.545000  19.79    39.430000   
2         23.1    35.090000  22.042857 ...   38.600000  22.60    36.194286   
3         24.5    40.900000  21.500000 ...   44.230000  22.60    44.090000   
4         18.6    41.663333  17.200000 ...   47.600000  16.70    46.000000   

    12.8      760.05         62       3.5    28   5.65   70  
0   8.47  764.166667  48.166667  8.000000  26.5  -1.92  210  
1  10.60  757.600000  57.000000  2.000000  27.0   2.40   50  
2  11.60  760.600000  63.000000  1.000000  40.0   4.67   50  
3  17.70  756.983333  63.000000  1.000000  21.5  10.40  250  
4   1.70  749.400000  97.000000  3.833333  32.5   1.25  180  

[5 rows x 26 columns]

In [9]:
colnames=['OBSERVATION', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'TEMP', 'PRE', 'RH_OUT', 'WS', 'V', 'TP', 'E']
data = pd.read_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/train1.csv', names=colnames, header=None)
data.head()

OBSERVATION         T1    RH_1         T2       RH_2         T3       RH_3  \
0         1111  22.700000  37.200  21.000000  38.000000  23.390000  37.290000   
1         1112  21.500000  41.045  20.500000  39.133333  22.926667  39.526667   
2         1113  21.666667  38.000  22.600000  35.700000  21.890000  36.590000   
3         1114  23.290000  38.530  21.671429  38.000000  24.290000  36.200000   
4         1115  24.000000  42.560  26.830000  34.356000  26.530000  40.333333   

          T4       RH_4         T5 ...        RH_8     T9       RH_9   TEMP  \
0  22.832857  34.942857  20.500000 ...   45.360000  20.20  38.663333  12.80   
1  21.700000  34.126667  18.633333 ...   34.663333  19.73  37.933333   8.47   
2  22.000000  35.530000  19.000000 ...   38.545000  19.79  39.430000  10.60   
3  23.100000  35.090000  22.042857 ...   38.600000  22.60  36.194286  11.60   
4  24.500000  40.900000  21.500000 ...   44.230000  22.60  44.090000  17.70   

          PRE     RH_OUT   WS     V     TP    E  
0  760.050000  62.000000  3.5  28.0   5.65   70  
1  764.166667  48.166667  8.0  26.5  -1.92  210  
2  757.600000  57.000000  2.0  27.0   2.40   50  
3  760.600000  63.000000  1.0  40.0   4.67   50  
4  756.983333  63.000000  1.0  21.5  10.40  250  

[5 rows x 26 columns]

In [10]:
X = data[['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'TEMP', 'PRE', 'RH_OUT', 'WS', 'V', 'TP']].values
Y = data[['E']].values

In [11]:
X = preprocessing.scale(X)

In [12]:
X

array([[ 0.63045563, -0.76890394,  0.30030269, ..., -0.22134904,
        -0.8788032 ,  0.44847926],
       [-0.11345087,  0.19628093,  0.07301206, ...,  1.61701811,
        -1.0058153 , -1.35309036],
       [-0.01013052, -0.56808524,  1.02763271, ..., -0.83413809,
        -0.96347793, -0.32498194],
       ..., 
       [ 0.32049459,  1.44010175,  0.43213126, ...,  0.11908932,
         0.95581595,  1.34807413],
       [ 1.74631537,  1.13636347,  1.6354728 , ..., -0.15326137,
         0.89936613,  1.79311181],
       [-0.49160333, -0.61828992, -0.29065295, ..., -0.5617874 ,
        -1.49975122, -0.80881167]])

In [19]:
Y

array([[-0.27042806],
       [ 1.11668517],
       [-0.46858709],
       ..., 
       [-0.46858709],
       [-0.36950757],
       [ 0.32404904]])

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, Y)

In [21]:
scaler = StandardScaler()

In [34]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
Y=Y.astype('int')

In [35]:
mlp = MLPClassifier(hidden_layer_sizes=(30, 30, 30, 30, 30, 30, 30, 30, 30, 30))
mlp.fit(X_train, y_train)

C:\Users\PRIYANSHU SHARMA\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: Unknown label type: (array([-0.46858709, -0.46858709, -0.46858709, ..., -0.17134854,
       -0.36950757,  3.49459356]),)

In [25]:
datatest = pd.read_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/test1.csv')
datatest.head()

50001       21.1       39.9      19.29      41.26       21.5       40.7  \
0  50002  22.600000  39.030000  20.790000  40.463333  22.290000  38.290000   
1  50003  21.000000  35.590000  19.790000  34.900000  21.166667  35.833333   
2  50004  20.566667  37.590000  20.566667  35.700000  20.166667  37.000000   
3  50005  21.500000  38.700000  18.566667  42.030000  22.500000  38.900000   
4  50006  22.290000  37.126667  20.150000  39.090000  23.500000  37.790000   

   18.89       41.2  18.08888889    ...         47.09       18.1   44.9   2.7  \
0  20.29  36.700000    20.760000    ...     39.266667  19.390000  37.50  7.27   
1  20.39  33.090000    18.000000    ...     34.126667  18.200000  39.79  6.05   
2  22.00  35.326667    17.700000    ...     36.966667  18.000000  41.29  9.35   
3  20.00  39.000000    19.633333    ...     45.326667  20.133333  43.20  3.03   
4  22.70  35.000000    20.390000    ...     43.560000  20.323333  40.20  9.97   

   733.6333333  98.16666667    2  34.83333333  2.43  7.37E+01  
0   756.666667    82.000000  2.0    40.000000  4.40      98.7  
1   751.250000    50.000000  6.5    34.500000 -3.70     150.0  
2   758.716667    58.333333  1.0    25.166667  1.48      88.3  
3   758.850000    95.000000  2.0    60.333333  2.25      62.6  
4   759.866667    66.666667  4.0    32.666667  4.00      60.2  

[5 rows x 26 columns]

In [26]:
colnames=['OBSERVATION', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'TEMP', 'PRE', 'RH_OUT', 'WS', 'V', 'TP', 'E']
datatest = pd.read_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/test1.csv', names=colnames, header=None)
datatest.head()

OBSERVATION         T1   RH_1         T2       RH_2         T3       RH_3  \
0        50001  21.100000  39.90  19.290000  41.260000  21.500000  40.700000   
1        50002  22.600000  39.03  20.790000  40.463333  22.290000  38.290000   
2        50003  21.000000  35.59  19.790000  34.900000  21.166667  35.833333   
3        50004  20.566667  37.59  20.566667  35.700000  20.166667  37.000000   
4        50005  21.500000  38.70  18.566667  42.030000  22.500000  38.900000   

      T4       RH_4         T5  ...         RH_8         T9   RH_9  TEMP  \
0  18.89  41.200000  18.088889  ...    47.090000  18.100000  44.90  2.70   
1  20.29  36.700000  20.760000  ...    39.266667  19.390000  37.50  7.27   
2  20.39  33.090000  18.000000  ...    34.126667  18.200000  39.79  6.05   
3  22.00  35.326667  17.700000  ...    36.966667  18.000000  41.29  9.35   
4  20.00  39.000000  19.633333  ...    45.326667  20.133333  43.20  3.03   

          PRE     RH_OUT   WS          V    TP      E  
0  733.633333  98.166667  2.0  34.833333  2.43   73.7  
1  756.666667  82.000000  2.0  40.000000  4.40   98.7  
2  751.250000  50.000000  6.5  34.500000 -3.70  150.0  
3  758.716667  58.333333  1.0  25.166667  1.48   88.3  
4  758.850000  95.000000  2.0  60.333333  2.25   62.6  

[5 rows x 26 columns]

In [27]:
X = datatest[['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'TEMP', 'PRE', 'RH_OUT', 'WS', 'V', 'TP']].values

In [28]:
datatest.tail()

OBSERVATION         T1       RH_1     T2       RH_2         T3  \
3940        53941  21.200000  46.200000  20.50  45.326667  21.694444   
3941        53942  21.166667  44.466667  20.50  42.060000  21.500000   
3942        53943  21.500000  40.500000  19.10  44.200000  22.500000   
3943        53944  21.290000  37.000000  20.29  35.933333  20.700000   
3944        53945  21.856667  44.663333  20.79  43.500000  23.182222   

           RH_3         T4       RH_4         T5  ...         RH_8         T9  \
3940  44.314444  19.790000  46.933333  18.600000  ...    51.296111  18.533333   
3941  43.590000  18.790000  43.126667  19.027778  ...    46.577222  19.100000   
3942  38.290000  20.790000  39.590000  20.100000  ...    43.163333  20.356667   
3943  37.290000  20.633333  35.066667  18.100000  ...    37.466667  18.500000   
3944  44.268333  21.500000  40.566667  18.890000  ...    43.260000  18.500000   

           RH_9  TEMP         PRE     RH_OUT        WS          V    TP      E  
3940  49.326667  9.17  763.666667  96.666667  4.333333  35.666667  8.67   90.2  
3941  44.900000  8.27  746.033333  73.166667  8.166667  40.000000  3.62  124.0  
3942  41.100000  7.70  751.933333  80.333333  4.000000  40.000000  4.50   68.6  
3943  41.790000  8.30  742.700000  63.000000  9.000000  29.000000  1.50  114.0  
3944  43.645000  5.40  762.600000  80.000000  4.000000  40.000000  2.10  187.0  

[5 rows x 26 columns]

In [29]:
X.shape
X = preprocessing.scale(X)

In [30]:
X[[3944]]

array([[ 0.09786788,  1.11380527,  0.20345903,  0.77279704,  0.45862452,
         1.52997335,  0.3132772 ,  0.36238408, -0.38681501,  0.33855459,
        -0.38181572,  0.68750059, -0.74556743, -0.05247036, -0.01090056,
         0.05905644, -0.48974309,  0.50164966, -0.37871584,  0.94631163,
         0.01799442, -0.01316869,  0.1608199 , -0.39572944]])

In [31]:
predicted_energy=[] 
for i in range (1,3945):
    #print(X[[i]]) 
    predictions = mlp.predict(X[[i]])
    print("ENERGY: %.3f" %predictions)
    predicted_energy.append(predictions)
    i+=1

NotFittedError: This MLPClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [19]:
for i in predicted_energy:
    print(i) 

[50]
[50]
[50]
[20]
[50]
[50]
[20]
[20]
[20]
[50]
[50]
[50]
[50]
[50]
[20]
[20]
[50]
[20]
[50]
[310]
[20]
[50]
[40]
[20]
[20]
[20]
[50]
[50]
[20]
[50]
[20]
[20]
[20]
[50]
[50]
[20]
[20]
[20]
[20]
[50]
[50]
[20]
[20]
[50]
[20]
[50]
[50]
[50]
[20]
[220]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[50]
[20]
[50]
[50]
[20]
[20]
[20]
[20]
[20]
[50]
[50]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[50]
[50]
[50]
[20]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[310]
[20]
[50]
[20]
[50]
[50]
[50]
[20]
[20]
[20]
[50]
[20]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[50]
[50]
[20]
[20]
[50]
[20]
[20]
[50]
[20]
[20]
[20]
[20]
[20]
[50]
[20]
[50]
[50]
[20]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[50]
[20]
[50]
[20]
[20]
[20]
[20]
[50]
[20]
[20]
[50]
[20]
[20]
[20]
[50]
[20]
[50]
[20]
[20]
[20]
[50]
[20]
[50]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[50]
[20]
[50]
[20]
[50]
[50]
[20]
[20]
[20]
[50]
[20]
[20]
[20]
[50]
[20]
[20]
[50]
[20]
[20]
[5

[20]
[20]
[20]
[50]
[20]
[20]
[50]
[50]
[20]
[20]
[50]
[50]
[20]
[20]
[50]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[50]
[310]
[50]
[50]
[20]
[50]
[20]
[20]
[310]
[50]
[50]
[20]
[50]
[50]
[20]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[50]
[50]
[20]
[20]
[20]
[20]
[20]
[50]
[20]
[20]
[50]
[50]
[50]
[20]
[20]
[50]
[50]
[20]
[20]
[50]
[20]
[20]
[50]
[20]
[20]
[50]
[50]
[50]
[20]
[50]
[50]
[20]
[20]
[20]
[50]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[20]
[50]
[50]
[20]
[20]
[20]
[50]
[50]
[20]
[20]
[20]
[20]
[50]
[50]
[20]
[20]
[20]
[20]
[20]
[20]
[50]
[20]
[50]
[20]
[20]
[50]
[20]
[50]
[20]
[20]
[20]
[50]
[20]
[20]
[50]
[20]
[50]
[20]
[20]
[20]
[50]
[50]
[50]
[50]
[50]
[20]
[20]
[50]
[50]
[50]
[50]
[20]
[50]
[20]
[20]
[50]
[20]
[50]
[20]
[50]
[50]
[50]
[50]
[50]
[20]
[50]
[20]
[20]
[50]
[20]
[20]
[20]
[50]
[20]
[50]
[20]
[20]
[20]
[20]
[50]
[50]
[20]
[20]
[50]
[20]
[20]
[20]
[50]
[20]
[20]
[40]
[20]
[20]
[20]
[50]
[50]
[20]
[310]
[20]
[20]
[20]
[20]
[20]
[50]
[20]
[20]
[20]
[2