In [1]:
#MULTIVARIATE LINEAR REGRESSION

In [2]:
import pandas as pd
from sklearn import preprocessing
data = pd.read_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/train1.csv')
data.head()

1111       22.7       37.2         21         38      23.39      37.29  \
0  1112  21.500000  41.045000  20.500000  39.133333  22.926667  39.526667   
1  1113  21.666667  38.000000  22.600000  35.700000  21.890000  36.590000   
2  1114  23.290000  38.530000  21.671429  38.000000  24.290000  36.200000   
3  1115  24.000000  42.560000  26.830000  34.356000  26.530000  40.333333   
4  1116  18.390000  43.363333  17.700000  42.433333  19.290000  42.500000   

   22.83285714  34.94285714       20.5 ...       45.36   20.2  38.66333333  \
0         21.7    34.126667  18.633333 ...   34.663333  19.73    37.933333   
1         22.0    35.530000  19.000000 ...   38.545000  19.79    39.430000   
2         23.1    35.090000  22.042857 ...   38.600000  22.60    36.194286   
3         24.5    40.900000  21.500000 ...   44.230000  22.60    44.090000   
4         18.6    41.663333  17.200000 ...   47.600000  16.70    46.000000   

    12.8      760.05         62       3.5    28   5.65   70  
0   8.47  764.166667  48.166667  8.000000  26.5  -1.92  210  
1  10.60  757.600000  57.000000  2.000000  27.0   2.40   50  
2  11.60  760.600000  63.000000  1.000000  40.0   4.67   50  
3  17.70  756.983333  63.000000  1.000000  21.5  10.40  250  
4   1.70  749.400000  97.000000  3.833333  32.5   1.25  180  

[5 rows x 26 columns]

In [3]:
colnames=['OBSERVATION', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'TEMP', 'PRE', 'RH_OUT', 'WS', 'V', 'TP', 'E']
data = pd.read_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/train1.csv', names=colnames, header=None)
data.head()

OBSERVATION         T1    RH_1         T2       RH_2         T3       RH_3  \
0         1111  22.700000  37.200  21.000000  38.000000  23.390000  37.290000   
1         1112  21.500000  41.045  20.500000  39.133333  22.926667  39.526667   
2         1113  21.666667  38.000  22.600000  35.700000  21.890000  36.590000   
3         1114  23.290000  38.530  21.671429  38.000000  24.290000  36.200000   
4         1115  24.000000  42.560  26.830000  34.356000  26.530000  40.333333   

          T4       RH_4         T5 ...        RH_8     T9       RH_9   TEMP  \
0  22.832857  34.942857  20.500000 ...   45.360000  20.20  38.663333  12.80   
1  21.700000  34.126667  18.633333 ...   34.663333  19.73  37.933333   8.47   
2  22.000000  35.530000  19.000000 ...   38.545000  19.79  39.430000  10.60   
3  23.100000  35.090000  22.042857 ...   38.600000  22.60  36.194286  11.60   
4  24.500000  40.900000  21.500000 ...   44.230000  22.60  44.090000  17.70   

          PRE     RH_OUT   WS     V     TP    E  
0  760.050000  62.000000  3.5  28.0   5.65   70  
1  764.166667  48.166667  8.0  26.5  -1.92  210  
2  757.600000  57.000000  2.0  27.0   2.40   50  
3  760.600000  63.000000  1.0  40.0   4.67   50  
4  756.983333  63.000000  1.0  21.5  10.40  250  

[5 rows x 26 columns]

In [4]:
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression

In [5]:
X = data[['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'TEMP', 'PRE', 'RH_OUT', 'WS', 'V', 'TP']].values
Y = data[['E']].values

In [6]:
X = preprocessing.scale(X)
X

array([[ 0.63045563, -0.76890394,  0.30030269, ..., -0.22134904,
        -0.8788032 ,  0.44847926],
       [-0.11345087,  0.19628093,  0.07301206, ...,  1.61701811,
        -1.0058153 , -1.35309036],
       [-0.01013052, -0.56808524,  1.02763271, ..., -0.83413809,
        -0.96347793, -0.32498194],
       ..., 
       [ 0.32049459,  1.44010175,  0.43213126, ...,  0.11908932,
         0.95581595,  1.34807413],
       [ 1.74631537,  1.13636347,  1.6354728 , ..., -0.15326137,
         0.89936613,  1.79311181],
       [-0.49160333, -0.61828992, -0.29065295, ..., -0.5617874 ,
        -1.49975122, -0.80881167]])

In [9]:
X.shape

(15780, 24)

In [10]:
Y

array([[ 70],
       [210],
       [ 50],
       ..., 
       [ 50],
       [ 60],
       [130]], dtype=int64)

In [11]:
regr = linear_model.LinearRegression()
regr.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [12]:
datatest = pd.read_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/test1.csv')
datatest.head()

50001       21.1       39.9      19.29      41.26       21.5       40.7  \
0  50002  22.600000  39.030000  20.790000  40.463333  22.290000  38.290000   
1  50003  21.000000  35.590000  19.790000  34.900000  21.166667  35.833333   
2  50004  20.566667  37.590000  20.566667  35.700000  20.166667  37.000000   
3  50005  21.500000  38.700000  18.566667  42.030000  22.500000  38.900000   
4  50006  22.290000  37.126667  20.150000  39.090000  23.500000  37.790000   

   18.89       41.2  18.08888889    ...         47.09       18.1   44.9   2.7  \
0  20.29  36.700000    20.760000    ...     39.266667  19.390000  37.50  7.27   
1  20.39  33.090000    18.000000    ...     34.126667  18.200000  39.79  6.05   
2  22.00  35.326667    17.700000    ...     36.966667  18.000000  41.29  9.35   
3  20.00  39.000000    19.633333    ...     45.326667  20.133333  43.20  3.03   
4  22.70  35.000000    20.390000    ...     43.560000  20.323333  40.20  9.97   

   733.6333333  98.16666667    2  34.83333333  2.43  6.00E+01  
0   756.666667    82.000000  2.0    40.000000  4.40     110.0  
1   751.250000    50.000000  6.5    34.500000 -3.70      60.0  
2   758.716667    58.333333  1.0    25.166667  1.48      80.0  
3   758.850000    95.000000  2.0    60.333333  2.25      50.0  
4   759.866667    66.666667  4.0    32.666667  4.00      60.0  

[5 rows x 26 columns]

In [13]:
colnames=['OBSERVATION', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'TEMP', 'PRE', 'RH_OUT', 'WS', 'V', 'TP', 'E']
datatest = pd.read_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/test1.csv', names=colnames, header=None)
datatest.head()

OBSERVATION         T1   RH_1         T2       RH_2         T3       RH_3  \
0        50001  21.100000  39.90  19.290000  41.260000  21.500000  40.700000   
1        50002  22.600000  39.03  20.790000  40.463333  22.290000  38.290000   
2        50003  21.000000  35.59  19.790000  34.900000  21.166667  35.833333   
3        50004  20.566667  37.59  20.566667  35.700000  20.166667  37.000000   
4        50005  21.500000  38.70  18.566667  42.030000  22.500000  38.900000   

      T4       RH_4         T5  ...         RH_8         T9   RH_9  TEMP  \
0  18.89  41.200000  18.088889  ...    47.090000  18.100000  44.90  2.70   
1  20.29  36.700000  20.760000  ...    39.266667  19.390000  37.50  7.27   
2  20.39  33.090000  18.000000  ...    34.126667  18.200000  39.79  6.05   
3  22.00  35.326667  17.700000  ...    36.966667  18.000000  41.29  9.35   
4  20.00  39.000000  19.633333  ...    45.326667  20.133333  43.20  3.03   

          PRE     RH_OUT   WS          V    TP      E  
0  733.633333  98.166667  2.0  34.833333  2.43   60.0  
1  756.666667  82.000000  2.0  40.000000  4.40  110.0  
2  751.250000  50.000000  6.5  34.500000 -3.70   60.0  
3  758.716667  58.333333  1.0  25.166667  1.48   80.0  
4  758.850000  95.000000  2.0  60.333333  2.25   50.0  

[5 rows x 26 columns]

In [14]:
X = datatest[['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'TEMP', 'PRE', 'RH_OUT', 'WS', 'V', 'TP']].values

In [15]:
X[[3944]]

array([[  21.85666667,   44.66333333,   20.79      ,   43.5       ,
          23.18222222,   44.26833333,   21.5       ,   40.56666667,
          18.89      ,   54.33111111,    5.59      ,   76.03      ,
          18.7       ,   35.09      ,   22.01111111,   43.26      ,
          18.5       ,   43.645     ,    5.4       ,  762.6       ,
          80.        ,    4.        ,   40.        ,    2.1       ]])

In [16]:
X = preprocessing.scale(X)
X

array([[-0.38204423, -0.08846296, -0.48898207, ..., -0.82474401,
        -0.27996039, -0.31655361],
       [ 0.56932338, -0.30805149,  0.20345903, ..., -0.82474401,
         0.1608199 ,  0.15610215],
       [-0.44546874, -1.17630959, -0.25816837, ...,  1.00130046,
        -0.30839782, -1.78730475],
       ..., 
       [-0.1283462 ,  0.0629774 , -0.57669128, ..., -0.01316869,
         0.1608199 ,  0.18009482],
       [-0.26153767, -0.82042473, -0.02735467, ...,  2.0157696 ,
        -0.77761555, -0.53968551],
       [ 0.09786788,  1.11380527,  0.20345903, ..., -0.01316869,
         0.1608199 , -0.39572944]])

In [ ]:
predicted_energy=[] 
for i in range (1,3945):
    print(X[[i]]) 
    energy_std = regr.predict(X[[i]])
    print("ENERGY: %.3f" %energy_std)
    predicted_energy.append(energy_std)
    i+=1


[[ 0.56932338 -0.30805149  0.20345903  0.0148133   0.00625613 -0.29081972
  -0.28328217 -0.52504758  0.63677941 -0.82100276 -0.03629625 -0.30032241
   0.11642569 -0.01381209  0.89223932 -0.70429649 -0.04265799 -0.95550076
  -0.02633037  0.15028162  0.15128337 -0.82474401  0.1608199   0.15610215]]
ENERGY: 98.203
[[-0.44546874 -1.17630959 -0.25816837 -1.37385285 -0.56328863 -1.03903521
  -0.23397974 -1.35357213 -0.87398027 -0.59991608 -0.11856279 -0.93558077
   0.40375673 -1.71709544  0.29320626 -1.68684257 -0.64044593 -0.41247806
  -0.25622891 -0.57643118 -1.98133975  1.00130046 -0.30839782 -1.78730475]]
ENERGY: 149.864
[[-0.72030827 -0.67150837  0.10036224 -1.17416449 -1.07030178 -0.68370899
   0.55978934 -0.84023882 -1.03819328 -0.63253543  0.17266076 -0.70456801
  -0.22358271 -0.85720667 -0.70518216 -1.14395719 -0.74091449 -0.05678634
   0.3656278   0.42531446 -1.42596915 -1.23053167 -1.10464608 -0.54448405]]
ENERGY: 87.812
[[-0.1283462  -0.39134369 -0.82289256  0.40586967  0.1127288

ENERGY: 94.051
[[ 0.75325445 -0.92390898  0.00342049 -0.41784482  0.1634302  -0.89995038
  -0.52979431 -0.16012956 -0.21712824 -0.84999774 -0.12953167 -0.13233258
  -0.50612489 -0.22449966 -0.10787047  0.4286263  -0.29382939 -0.60850372
  -0.09228487  0.10332479  0.90658739 -0.48658763 -0.08089832  0.51119378]]
ENERGY: 48.106
[[-0.5152357   0.18917771 -1.08448142  1.05402481  0.36623546  0.10511521
  -0.13044465 -0.02012957  0.34666976 -0.09685328 -0.67797527  0.05609423
   0.35586822  0.4800473  -0.27484232 -0.84347686  0.54843205  0.58583004
  -0.50120277 -0.51829416  0.69554656  0.32498769  0.1608199  -0.13180999]]
ENERGY: 90.180
[[ 1.20356845 -0.72871917  0.80819092 -0.82720596  0.97465123 -1.06867957
   1.64444274 -0.93127707  1.86290322 -1.41938655  0.46827187 -1.22159148
   1.60096939 -1.10139807  1.93125182 -1.45643488  1.66530755 -1.79967577
   0.73308859  0.72047166 -1.09274679 -0.41895635 -0.62120964  0.19928897]]
ENERGY: 113.045
[[ 0.75325445 -0.76994461  0.85435366 -1.2490

[[ 0.01753017 -0.9886918   0.26654811 -1.1408831   1.66756919 -0.35985453
  -0.42625921 -0.29553939  0.22077312  2.4989218   0.83134153 -1.72095998
  -0.41513673 -0.82370284  0.18476062 -0.71257995 -0.04265799 -0.66383354
   0.54464716  0.51699207 -1.05942455 -0.5542189  -1.1188648  -0.00704806]]
ENERGY: 200.740
[[-0.83235823 -0.87342886 -1.26913238 -0.17572268 -1.10410265 -0.62279593
   0.25904453 -0.74767052 -0.8192426   0.33734646 -0.67194239 -0.07337564
  -0.98500996 -0.09628307 -0.86526858  0.21771661 -1.09757788 -0.88673369
  -1.0062258  -0.48922564  0.10685372 -1.23053167 -1.3463643  -1.08359952]]
ENERGY: 57.816
[[-0.5575187   1.14577602 -0.01196709  0.71289053 -0.43146522  1.45738528
  -0.57416649  1.58642774 -0.16786433  0.50823559  0.60154366  0.40052688
  -0.73838415  1.07270004 -0.53304623  0.94995345 -0.29382939  1.28930922
   0.62002373 -0.89618481 -0.47073171  2.15103216  0.1608199   0.53998499]]
ENERGY: 120.246
[[ 0.16552068  0.66873887  0.39272626  0.37342031  0.112728

[[-0.31861972 -0.71946449 -0.99215594 -0.06922222 -0.59708951 -0.39944802
  -0.21590219 -1.20668689 -0.76450494  0.01586468 -1.10960039  0.20396808
  -0.31457087 -0.11045777 -0.22320154  0.03930357 -0.67393545 -0.25992584
  -1.14190363  1.01339282  0.41786126 -1.23053167  1.56847306 -1.07952076]]
ENERGY: 61.730
[[-0.21925466  0.87065935  0.34656352  0.24861509 -0.59708951  0.9274416
  -0.82067863  1.38675562  0.85573009  4.70121091 -0.5298955   1.23223704
  -0.08577022  0.78319256  0.64952765  0.2540364  -0.29382939  0.02304669
  -0.4917807  -1.21817448  1.01766151 -0.68948145 -1.40323918  0.06013143]]
ENERGY: 133.072
[[-0.26153767 -0.82042473 -0.11506388 -0.79974881 -0.70356227 -0.83599166
  -0.13044465 -1.12406394  0.9400261   4.23209639 -0.81344084  0.19744108
  -0.74556743 -0.67100267 -0.6569841  -0.71831465 -0.94185161 -1.47955322
  -0.80270906 -0.56748702  0.04020925 -0.82474401 -1.47433277 -0.87958978]]
ENERGY: 94.476
[[-0.69916677 -0.35769028 -0.45666816 -0.21898849 -0.4500557 

ENERGY: 78.108
[[-0.08077782 -1.52146742 -0.39204032 -1.42377494 -0.70356227 -1.30299183
  -0.59060063 -1.36045738 -0.27186591 -1.43714597 -1.09863152 -0.03592568
   0.64319926 -2.10651308  0.34484704 -2.12013138 -0.56174556 -0.46701746
  -1.04768291  1.9547654  -0.94835043 -0.5542189   0.1608199  -1.84728645]]
ENERGY: 124.556
[[ 0.05558487  0.72594967  0.10036224  0.85433645 -0.39428425  0.9274416
   0.3132772   0.94150973  0.08611845  0.70203075 -0.37633129  1.0695972
  -0.46302524  1.34051595 -0.12508406  1.01611495 -0.48974309  0.61902793
  -0.43524827 -0.2656217   1.15095046 -1.23053167 -1.54542637  0.2040875 ]]
ENERGY: 65.560
[[ 0.50589887 -1.67185612  0.30040078 -1.85643306  0.46763809 -1.05223304
   0.99858094 -1.45389999  0.6896925   1.04554871  0.24944287 -1.6055071
   0.82421782 -1.19482222  0.44296453 -1.07514073  0.3140054  -1.75541191
   0.41273816  1.21016429 -1.49261362  0.12209386  0.1608199  -0.53968551]]
ENERGY: 120.510
[[-0.1283462  -1.02234522 -0.7336446  -0.375411

In [ ]:
for i in predicted_energy:
    print(i) 

In [ ]:
import numpy as np
predicted_energy=np.array([],dtype = float)
for i in range (0,3945):
    print(X[[i]]) 
    energy_std = regr.predict(X[[i]])
    print("ENERGY: %.3f" %energy_std)
    predicted_energy = np.append(predicted_energy, energy_std)
    i+=1

In [ ]:
predicted_energy

In [ ]:
predicted_energy.shape

In [ ]:
np.savetxt("C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/foo.csv", predicted_energy, delimiter=",")

In [ ]:
colnames=['OBSERVATION', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'TEMP', 'PRE', 'RH_OUT', 'WS', 'V', 'TP', 'E']
datatest = pd.read_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/test1.csv', names=colnames, header=None)
datatest.head()

In [ ]:
datatest.to_csv('C:/Users/PRIYANSHU SHARMA/Desktop/PRIYANSHU/6 STUDY/6 SEMSTER/MACHINE LEARNING/EXTRA/energy/final2.csv', encoding='utf-8', index=False)